version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Limit the number of open PRs to avoid noise
    open-pull-requests-limit: 10
    # Specify labels for npm pull requests
    labels:
      - "dependencies"
      - "npm"
    # Specify the versioning strategy
    versioning-strategy: auto
    # Group all minor and patch updates in a single PR
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
    # Set reviewers for PR approval
    reviewers:
      - "project-maintainer"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions" 